### ISSUE TITLE
[web] createElement is not a function

### ISSUE THREAD

**Issue by Naturalclar** [react-native-picker/react-native-picker#103]
# Bug report

## Summary

trying to use the Picker element with `react-native-web` version 0.12+ results in error `createElement is not a function`

This is because in react-native-web 0.12+, `createElement` is renamed to `unstable_createElement`

Since expo is using react-native-web v0.11, which still has `createElement` exported, it would be nice if there is a way for both `expo-web` users and `react-native-web` users to be able to use the picker component without any issues.

## Environment info

Library version: 
react-native-web: 0.12.2

## Steps to reproduce

1. Use `Picker` component in web

Describe what you expected to happen:

1. expect Picker to work in both `expo-web` and `react-native-web` projects

## Reproducible sample code

```
import * as React from 'react';
import {Picker} from '@react-native-community/picker';

type Props = {};
export const YearMonthPicker: React.FC<Props> = () => {
  return (
    <Picker selectedValue={'test'}>
      <Picker.Item value={'test'}>Test</Picker.Item>
    </Picker>
  );
};
```

**Comment by nandorojo** [comment]
I'm getting this error when I import the `Picker`.

```sh
error - ./node_modules/@react-native-community/picker/js/Picker.web.js
Attempted import error: 'unstable_createElement' is not exported from 'react-native-web/dist/index'.
```

**Comment by d4rky-pl** [comment]
I'm running into the opposite of above issue and there is nothing I can do to fix it with Expo SDK 39:

```
Failed to compile.

./node_modules/@react-native-community/picker/js/Picker.web.js
Attempted import error: 'createElement' is not exported from 'react-native'.
```

**Comment by d4rky-pl** [comment]
@Naturalclar this is still an issue

**Comment by Naturalclar** [comment]
@nandorojo @d4rky-pl sorry for closing the issue
for using this package with managed workflow of expo, you'd need to install the specific version specified by expo, by using `expo install @react-native-community/picker` .

The latest version of this package is intended for regular react-native-cli or bare workflow of expo.

using expo sdk ver 39 should be able to address the issue. otherwise, please continue using v1.7.0 of this package.

Thanks!
